server:
  port: 8080
  netty:
    connection-timeout: 10s
    idle-timeout: 60s
  compression:
    enabled: true
    mime-types: application/json,text/plain
    min-response-size: 1024
spring:
  application:
    name: api-gateway
  jmx:
    enabled: false
  http:
    codecs:
      max-in-memory-size: 5MB
service:
  url:
    user-service: "lb://user-service"
    wallet-service: "lb://wallet-service"
    transaction-service: "lb://transaction-service"
    notification-service: "lb://notification-service"

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,routes
  endpoint:
    health:
      show-details: always
  health:
    gateway:
      enabled: true
internal:
  secret: "${INTERNAL_SECRET}"
jwt:
  secret-key: "${JWT_SECRET_KEY}"

eureka:
  client:
    service-url:
      defaultZone: "${EUREKA_SERVER_URL:http://${EUREKA_USER}:${EUREKA_PASSWORD}@localhost:8761/eureka/}"
  instance:
    prefer-ip-address: true
