server:
  port: 8081
  tomcat:
    threads:
      max: 300
      min-spare: 20
    accept-count: 200
spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/user_service
    username: Tienld
    password: 123456
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      connection-timeout: 5000
      idle-timeout: 300000
      max-lifetime: 600000
  jpa:
    hibernate:
      ddl-auto: update   # validate | update | create | create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

service:
  wallet-service:
    url: "http://localhost:8082"
  notification-service:
    url: "http://localhost:8085"
internal:
  secret: "${INTERNAL_SECRET}"
jwt:
  secret-key: "${JWT_SECRET_KEY}"
qr:
  secret-key: "${QR_SECRET_KEY}"
otp:
  token-expiration-minutes: 10
