server:
  port: "${EUREKA_PORT:8761}"

spring:
  application:
    name: eureka-server
  jmx:
    enabled: false

eureka:
  auth:
    username: "${EUREKA_USER}"
    password: "${EUREKA_PASSWORD}"
  instance:
    hostname: "${EUREKA_HOSTNAME:localhost}"
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 15000
